import React from "react";

const experiences = [
  {
    duration: "Apr 2024 - Present",
    title: "LLM Programming Analyst",
    company: "Freelancer with DataAnnotationTech",
    location: "Remote",
    highlights: [
      "Analyze and improve the quality of responses and code generated by various LLMs in data analysis, AI, and Machine Learning, as well as software developments in JavaScript/TypeScript and Python, etc.",
      "Solve complex problems in the domains above as needed, to train the models to provide accurate and helpful responses, as many users are professionals like data scientists and software developers seeking solutions for problems encountered in their work.",
      "Create comprehensive reports in professional writing with sophisticated visualizations.",
    ],
    tags: ["Data Science", "AI", "Machine Learning", "Deep Learning"],
  },
  {
    duration: "Sep 2022 - Present",
    title: "Web Developer",
    company: "Freelance",
    location: "Remote",
    highlights: [
      "Independently design and develop web apps that fully satisfy client requirements.",
      "Deliver advanced functionalities including ecommerce, OAuth and natural animations within the MERN stack, NextJS, Flask, or Django.",
    ],
    tags: ["next-js", "MERN", "PostgreSQL", "Django", "Flask"],
  },
  {
    duration: "Jul 2024 - Aug 2024",
    title: "Web Developer Intern",
    company: "Evergreen Investments",
    location: "Remote",
    highlights: [
      "Led a team of interns to design and develop a full-stack web application using the MERN stack.",
      "Collaborated on data analytics tasks, integrating property and customer data into the website.",
      "Implemented AWS Lambda and S3 for building scalable data pipelines.",
    ],
    tags: ["MERN", "AWS Lambda", "AWS S3", "Rest API"],
  },
];

const Experience = () => {
  return (
    <main className="mb-auto px-40 md:px-60 lg:px-80">
      <div className="divide-y divide-gray-200 dark:divide-gray-700">
        <div className="space-y-2 pb-8 pt-6 md:space-y-5">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-700 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
            Experience
          </h1>
        </div>
        <ul className="divide-y divide-gray-200 dark:divide-gray-700">
          {experiences.map((exp, index) => (
            <li key={index} className="py-12">
              <article>
                <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                  <dl>
                    <dt className="sr-only">Duration</dt>
                    <dd className="text-base font-medium leading-6 text-gray-700 dark:text-gray-500">
                      {exp.duration}
                    </dd>
                    <dd className="italic text-gray-500 dark:text-gray-400">
                      {exp.company}, {exp.location}
                    </dd>
                  </dl>
                  <div className="space-y-5 xl:col-span-3">
                    <div className="space-y-6">
                      <div>
                        <h2 className="text-2xl font-bold leading-8 tracking-tight">
                          <a
                            className="text-gray-900 dark:text-gray-600"
                            href={exp.href}
                          >
                            {exp.title}
                          </a>
                        </h2>
                        <div className="flex flex-wrap">
                          {exp.tags.map((tag, index) => (
                            <a
                              key={index}
                              className="mr-3 text-sm font-medium uppercase text-primary-500 hover:text-primary-600 dark:hover:text-primary-400"
                              href={`/tags/${tag}`}
                            >
                              {tag}
                            </a>
                          ))}
                        </div>
                      </div>
                      <ul className="list-disc list-inside prose max-w-none text-gray-700 dark:text-gray-500">
                        {exp.highlights.map((highlight, idx) => (
                          <li key={idx}>{highlight}</li>
                        ))}
                      </ul>
                    </div>
                    {/* <div className="text-base font-medium leading-6">
                      <a
                        className="text-primary-500 hover:text-primary-600 dark:hover:text-primary-400"
                        aria-label={`Read more: "${exp.title}"`}
                        href={exp.href}
                      >
                        Read more →
                      </a>
                    </div> */}
                  </div>
                </div>
              </article>
            </li>
          ))}
        </ul>
      </div>

      <div className="flex items-center justify-center pt-8"></div>
    </main>
  );
};

export default Experience;
